// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qffect.Infrastructure.Persistence;

#nullable disable

namespace Qffect.Infrastructure.Migrations.Settings
{
    [DbContext(typeof(QffectSettingsDbContext))]
    [Migration("20251106043608_InitialSettingsDb")]
    partial class InitialSettingsDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ADM")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qffect.Infrastructure.Persistence.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("TenantId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", "ADM");
                });

            modelBuilder.Entity("Qffect.Infrastructure.Persistence.TenantModuleSetting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModuleCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId", "ModuleCode");

                    b.ToTable("TenantModuleSettings", "ADM");
                });

            modelBuilder.Entity("Qffect.Infrastructure.Persistence.TenantModuleSetting", b =>
                {
                    b.HasOne("Qffect.Infrastructure.Persistence.Tenant", null)
                        .WithMany("ModuleSettings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qffect.Infrastructure.Persistence.Tenant", b =>
                {
                    b.Navigation("ModuleSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
